service: hub-search-proxy
custom:
  bucketBaseName: serverless-shared-bucket
  ResearchHub: ${self:service}
  BusinessService: Faculty of Science
  Department: Centre for eResearch
  ProjectCode: N/A
  WikiLink: https://wiki.auckland.ac.nz/display/APPLCTN/Research+Hub
  Application: ${self:service}
  CostCentre: N/A
  Faculty: Science
  customDomain:
    domainName: ${file(env/${self:provider.stage}.json):infra.awsApiGatewayCustomDomainName}
    basePath: ${self:service}
    stage: ${self:provider.stage}
provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'} # Deploy with sls deploy --stage STAGE (default dev)
  region: ap-southeast-2
  endpointType: regional
  role: arn:aws:iam::${file(env/${self:provider.stage}.json):awsAccountId}:${file(env/${self:provider.stage}.json):lambdaRole}
  tags:
    ResearchHub: ${self:custom.ResearchHub}
    BusinessService: ${self:custom.BusinessService}
    Department: ${self:custom.Department}
    ProjectCode: ${self:custom.ProjectCode}
    WikiLink: ${self:custom.WikiLink}
    Application: ${self:custom.Application}
    CostCentre: ${self:custom.CostCentre}
    Faculty: ${self:custom.Faculty}
  stackTags:
    ResearchHub: ${self:custom.ResearchHub}
    BusinessService: ${self:custom.BusinessService}
    Department: ${self:custom.Department}
    ProjectCode: ${self:custom.ProjectCode}
    WikiLink: ${self:custom.WikiLink}
    Application: ${self:custom.Application}
    CostCentre: ${self:custom.CostCentre}
    Faculty: ${self:custom.Faculty}
  deploymentBucket:
    name: ${self:custom.bucketBaseName}-${self:provider.stage}
  environment:
    # Environment variables available to all functions in this service
    LEVEL: INFO
    ELASTICSEARCH_ENDPOINT: ${file(env/${self:provider.stage}.json):ELASTICSEARCH_ENDPOINT}
  apiGateway:
    apiKeySourceType: HEADER
  apiKeys:
    - name: ${self:service}-${self:provider.stage}-apiKey


  iamRoleStatements:
    - Effect: Allow
      Action:
        - ssm:GetParameter
        - ssm:GetParameters
      Resource:
        - arn:
          Fn::Join:
            - ":"
            - - arn
              - aws
              - ssm:${self:provider.region}
              - ${file(env/${self:provider.stage}.json):awsAccountId}
              - parameter/${self:provider.stage}/research-hub/*
    - Effect: Allow
      Action:
        - kms:Decrypt
      Resource:
        - arn:
          Fn::Join:
            - ":"
            - - arn
              - aws
              - kms
              - ${self:provider.region}
              - ${file(env/${self:provider.stage}.json):awsAccountId}
              - ${file(env/${self:provider.stage}.json):resourceKey}
    - Effect: Allow
      Action:
        - es:ESHttp*
      Resource:
        - arn:
          Fn::Join:
            - ":"
            - - arn
              - aws
              - es
              - ${self:provider.region}:518380838815
              - domain/${file(env/${self:provider.stage}.json):elasticsearchDomainName}/*
              # NOTE: hardcoded account id of the es domain - change to prod account id once es is deployed to prod
package:
  exclude:
    - .git/**
    - .vscode/*
    - events/*
    - node_modules/**
    - "!node_modules/@uoa/**"
    - "!node_modules/uuid/**"
functions:
  hub-search-proxy:
    handler: handler.search
    events:
      - http:
          path: /
          method: post
          cors: 
            true
  hub-search-proxy-put-doc:
    handler: handler.indexDoc
    events:
      - http:
          path: index-doc
          method: put
          cors: 
            true
          private: true
            
plugins:
  - serverless-offline
  - serverless-mocha-plugin
  - serverless-domain-manager
